-- Tabela para armazenar dados de autuações do IBAMA
CREATE TABLE public.autuacoes_ibama (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpf_cnpj TEXT,
  nome_autuado TEXT,
  data_auto DATE,
  valor_multa NUMERIC,
  descricao_infracao TEXT,
  municipio TEXT,
  uf TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Adiciona um comentário à tabela para documentação
COMMENT ON TABLE public.autuacoes_ibama IS 'Armazena dados históricos de autuações ambientais emitidas pelo IBAMA.';



-- Tabela para armazenar um catálogo de legislação ambiental
CREATE TABLE public.legislacao_ambiental (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT NOT NULL,
  resumo TEXT,
  tipo_norma TEXT,
  orgao_emissor TEXT,
  link_oficial TEXT,
  palavras_chave TEXT[], -- Usamos um array de texto para as palavras-chave
  embedding VECTOR(384), -- Coluna para busca semântica. O tamanho (384) depende do modelo de embedding que usaremos.
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Adiciona um comentário à tabela para documentação
COMMENT ON TABLE public.legislacao_ambiental IS 'Catálogo de leis, decretos e normas ambientais para consulta pelo chatbot.';


-- Tabela para funcionar como um dicionário de termos técnicos e siglas
CREATE TABLE public.termos_glossario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  termo TEXT NOT NULL UNIQUE, -- UNIQUE garante que não teremos o mesmo termo duas vezes
  definicao TEXT NOT NULL,
  categoria TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Adiciona um comentário à tabela para documentação
COMMENT ON TABLE public.termos_glossario IS 'Glossário de termos técnicos e siglas da área ambiental para consulta rápida.';


-- Tabela para armazenar dados de Termos de Embargo emitidos pelo IBAMA
CREATE TABLE public.termos_embargo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf_cnpj TEXT,
    nome_embargado TEXT,
    data_embargo DATE,
    justificativa TEXT,
    municipio TEXT,
    uf TEXT,
    wkt_geometria TEXT, -- Coluna para dados geoespaciais futuros
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Adiciona um comentário para documentação
COMMENT ON TABLE public.termos_embargo IS 'Armazena dados históricos de Termos de Embargo emitidos pelo IBAMA.';


-- Tabela para armazenar o status de Pessoas Jurídicas no Cadastro Técnico Federal (CTF/APP)
CREATE TABLE public.cadastro_tecnico_federal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj TEXT NOT NULL,
    razao_social TEXT,
    situacao_cadastro TEXT,
    data_situacao_cadastral DATE,
    uf TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Adiciona um comentário para documentação
COMMENT ON TABLE public.cadastro_tecnico_federal IS 'Relação de PJs inscritas no CTF/APP, com seu status cadastral.';